steps/etcd/libvirt: Fix obsolete local.etcd_count reference
I'd missed this line in b5bf060 (modules/*/target-defaults:
Consolidate default counts for etcd, 2018-07-23, #74).  Fixing it
avoids `tectonic install` dying with:

  Error: libvirt_volume.etcd: local.etcd_count: no local value of this
  name has been declared