libvirt/main.tf: Add correct entry for *api-int* hostname
   libvirt breaks api-int changes due to commit 60526fe3760d10b561ca99f46a9e2afec30f801b

   Error: data.libvirt_network_dns_host_template.bootstrap: resource repeated multiple times