image: Asset generation is required
Assets are required to build, but hack/build-go.sh cannot handle
cross architecture asset generation. Explicitly generate before
invoking the script.

Failed when CI tried to build:

+ go build ... ./cmd/openshift-install
data/unpack.go:12:15: undefined: Assets