images/upi-installer: pin version of pyopenssl
Newer versions removed `load_pkcs12` causing `gsutil` to fail with the
unhelpful message:
```
CommandException: The signurl command requires the pyopenssl library (try pip install pyopenssl or easy_install pyopenssl)
```