terraform/exec/plugins/vendor: Bump terraform-provider-aws to v2.2.0
This picks up a bunch of upstream improvements [1] including [2] to
address [3].

Generated with a manual Gopkg.toml edit followed by:

  $ cd terraform/exec/plugins
  $ dep ensure

with:

  $ dep version
  dep:
   version     : v0.5.1
   build date  : 2019-03-20
   git hash    : faa61893
   go version  : go1.10.3
   go compiler : gc
   platform    : linux/amd64
   features    : ImportDuringSolve=false

The aws-iam-authenticator pin gets us closer to [4], although (1) I
don't know why dep isn't figuring that out for itself and (2) they got
rid of their 0.3.1 tag [5]?  Anyway, this avoids:

  $ hack/build.sh
  ...
  # github.com/openshift/installer/pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-aws/aws
  pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-aws/aws/data_source_aws_eks_cluster_auth.go:35:38: too many arguments in call to token.NewGenerator
  have (bool)
  want ()
  ...

The AWS SDK pin gets us closer to [6] and avoids:

  $ hack/build.sh
  ...
  # github.com/openshift/installer/pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-aws/aws
  pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-aws/aws/structure.go:4801:7: spec.ServiceNames undefined (type *appmesh.VirtualRouterSpec has no field or method ServiceNames)
  ...

The = prefixes in Gopkg.toml settle things down, because [7]:

  Note: When you specify a version without an operator, dep
  automatically uses the ^ operator by default. dep ensure will
  interpret the given version as the min-boundary of a range...

[1]: https://github.com/terraform-providers/terraform-provider-aws/blob/v2.2.0/CHANGELOG.md
[2]: https://github.com/terraform-providers/terraform-provider-aws/pull/7734 (v2.0.0)
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1659970
[4]: https://github.com/terraform-providers/terraform-provider-aws/blob/v2.2.0/go.mod#L27
[5]: https://github.com/kubernetes-sigs/aws-iam-authenticator/tags
[6]: https://github.com/terraform-providers/terraform-provider-aws/blob/v2.2.0/go.mod#L7
[7]: https://golang.github.io/dep/docs/Gopkg.toml.html#version-rules