installer/pkg: Lowercase some capitalized error messages
Errors should not be capitalized [1].  We haven't been picking these
up in our golint CI, because error-cap violations have a confidence of
0.6 [2] (vs. the default 0.8 [3]).  This commit avoids:

  $ golint -min_confidence 0.6 ./installer/...
  installer/pkg/config/parser.go:37:27: error strings should not be capitalized or end with punctuation or a newline
  installer/pkg/workflow/executor.go:31:2: error strings should not be capitalized or end with punctuation or a newline
  installer/pkg/workflow/terraform.go:13:21: error strings should not be capitalized or end with punctuation or a newline
  installer/pkg/workflow/terraform.go:18:21: error strings should not be capitalized or end with punctuation or a newline
  installer/pkg/workflow/utils.go:56:21: error strings should not be capitalized or end with punctuation or a newline
  installer/pkg/workflow/utils.go:78:21: error strings should not be capitalized or end with punctuation or a newline
  installer/pkg/workflow/utils.go:93:21: error strings should not be capitalized or end with punctuation or a newline

I've also fixed a number of TerraForm -> Terraform typos (maybe they
re-branded upstream at some point?).  Upstream references to the
project prefer the Terraform capitalization (e.g. [4]).  I've
downcased the "terraform not in executable..." error message to make
golint happy, and using a lowercase form matches the command name we
were searching for ('terraform' the command, vs. 'Terraform' the
project).

[1]: https://github.com/golang/go/wiki/CodeReviewComments#error-strings
[2]: https://github.com/golang/lint/blob/06c8688daad7faa9da5a0c2f163a3d14aac986ca/lint.go#L1186
[3]: https://github.com/golang/lint/blob/06c8688daad7faa9da5a0c2f163a3d14aac986ca/golint/golint.go#L23
[4]: https://www.terraform.io/