pkg/terraform/exec/plugins/vendor: Roll back libvirt to 2ad0228349
The final pull request landing in the provider's v0.5.1 broke the
installer on my libvirt 3.9.0 [1]:

  libvirt_ignition.master: Creating...
    ...
  module.volume.libvirt_volume.coreos_base: Creating...
    ...
  libvirt_network.net: Creating...
    ...
  module.bootstrap.libvirt_ignition.bootstrap: Creating...
    ...
  libvirt_ignition.master: Creation complete after 0s (ID: /home/trking/VirtualMachines/wking-mast...n;5c1b382d-27af-08b2-1fff-8dafabae17c3)
  module.bootstrap.libvirt_ignition.bootstrap: Still creating... (10s elapsed)
  module.bootstrap.libvirt_ignition.bootstrap: Still creating... (20s elapsed)
  module.bootstrap.libvirt_ignition.bootstrap: Still creating... (30s elapsed)
  ...
  module.bootstrap.libvirt_ignition.bootstrap: Still creating... (5m0s elapsed)

  Error: Error applying plan:

  3 error(s) occurred:

  * libvirt_network.net: 1 error(s) occurred:

  * libvirt_network.net: Error clearing libvirt network: virError(Code=38, Domain=7, Message='End of file while reading data: Input/output error')
  * module.volume.libvirt_volume.coreos_base: 1 error(s) occurred:

  * libvirt_volume.coreos_base: Error creating libvirt volume: virError(Code=38, Domain=7, Message='End of file while reading data: Input/output error')
  * module.bootstrap.libvirt_ignition.bootstrap: 1 error(s) occurred:

  * libvirt_ignition.bootstrap: Error creating libvirt volume for Ignition wking-bootstrap.ign: virError(Code=1, Domain=7, Message='internal error: client socket is closed')

Roll back to keep the lock that was dropped upstream until we
understand this better.

Generated with:

  $ cd pkg/terraform/exec/plugins
  $ emacs Gopkg.toml  # adjust to pin to 2ad0228349
  $ dep ensure

using:

  $ dep version
  dep:
   version     : v0.5.0
   build date  :
   git hash    : 22125cf
   go version  : go1.10.3
   go compiler : gc
   platform    : linux/amd64
   features    : ImportDuringSolve=false

[1]: https://github.com/dmacvicar/terraform-provider-libvirt/pull/495#issuecomment-448891285