platformtests/aws/default_instance_class_test: Add Bahrain (me-south-1)
The region was added on 2019-07-29 [1] and the canonical ID is
me-south-1 [2].  This fixes:

  $ cd platformtests/aws
  $ AWS_PROFILE=openshift-dev go test .
  --- FAIL: TestGetDefaultInstanceClass (71.40s)
      --- FAIL: TestGetDefaultInstanceClass/Middle_East_(Bahrain) (0.00s)
      		default_instance_class_test.go:99: not a recognized region
  FAIL
  FAIL		github.com/openshift/installer/platformtests/aws				71.420s

And as a new region without m4 support, we need to set its default to
m5 to avoid:

  $ AWS_PROFILE=openshift-dev go test .
  --- FAIL: TestGetDefaultInstanceClass (75.95s)
      --- FAIL: TestGetDefaultInstanceClass/Middle_East_(Bahrain) (1.96s)
      default_instance_class_test.go:107: no direct access to region, assuming full support: AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: f05f9e76-2a63-40d1-8748-a67f6d637ba1
      default_instance_class_test.go:121: map[m5:{} m5d:{} t3:{}]
      default_instance_class_test.go:122:
        Error Trace:default_instance_class_test.go:122
        Error:      Not equal:
                    expected: "m4"
                    actual  : "m5"

                    Diff:
                    --- Expected
                    +++ Actual
                    @@ -1 +1 @@
                    -m4
                    +m5
        Test:       TestGetDefaultInstanceClass/Middle_East_(Bahrain)
  FAIL
  FAIL  github.com/openshift/installer/platformtests/aws75.965s

[1]: https://aws.amazon.com/about-aws/whats-new/2019/07/announcing-the-new-aws-middle-east--bahrain--region-/
[2]: https://github.com/aws/aws-sdk-go/commit/384f4536edd1f4b59cf0c03ab3b346aba4c1c9cc#diff-fe3b36d57dc4378fa7b13c85492f4119R49