cmd/openshift-install: suppress glog output
glog is polluting the output of the installer with messages like the
following:

    ERROR: logging before flag.Parse: E0201 13:56:32.940927

By telling the flag parser to parse nothing, the "logging before
flag.Parse" portion is removed. By setting 'stderrthreshold', the rest
of the error message is also suppressed.