tests/smoke: Drop kubectl dependencies
And use the (hopefully more stable) client-go and apimachinery
analogs.  Also transition to kubernetes.Interface, which is more
generic than *Clientset.  These changes avoid:

  $ go test ./tests/smoke/
  # github.com/openshift/installer/tests/smoke
  tests/smoke/cluster_test.go:319:25: cannot use cfg (type clientcmd.ClientConfig) as type genericclioptions.RESTClientGetter in argument to util.NewFactory:
      clientcmd.ClientConfig does not implement genericclioptions.RESTClientGetter (missing ToDiscoveryClient method)
  tests/smoke/cluster_test.go:321:28: too many arguments in call to f.Validator
      have (bool, string)
      want (bool)
  tests/smoke/cluster_test.go:326:25: f.UnstructuredObject undefined (type util.Factory has no field or method UnstructuredObject)
  tests/smoke/cluster_test.go:331:31: too many arguments in call to "github.com/openshift/installer/tests/smoke/vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource".NewBuilder
  tests/smoke/cluster_test.go:331:41: f.CategoryExpander undefined (type util.Factory has no field or method CategoryExpander)
  tests/smoke/cluster_test.go:331:69: undefined: "github.com/openshift/installer/tests/smoke/vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource".ClientMapperFunc
  tests/smoke/cluster_test.go:401:20: info.VersionedObject undefined (type *"github.com/openshift/installer/tests/smoke/vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource".Info has no field or method VersionedObject)
  FAIL    github.com/openshift/installer/tests/smoke [build failed]

due to our recent vendor version bumps.

Also move from Core() to CoreV1() to catch up with
kubernetes/kubernetes@c679fee1 (Update staging client-go, 2016-11-08,
kubernetes/kubernetes#36465) which deprecated the unversioned Core().