Revert "Revert "data/aws: Switch to m4.large""
Even though we got our AWS quota increased, it looks like AWS just
doesn't have the physical capacity for these machines in us-east-1. We
are seeing a lot of failures in CI:

```
Error: Error applying plan:

1 error occurred:
    * module.masters.aws_instance.master[0]: 1 error occurred:
    * aws_instance.master.0: Error launching source instance: timeout
      while waiting for state to become 'success' (timeout: 30s)
```

Looking at CloudTrail, I see the following error, which corresponds to
that failure:

> We currently do not have sufficient t3.medium capacity in the
> Availability Zone you requested (us-east-1a). Our system will be
> working on provisioning additional capacity. You can currently
> get t3.medium capacity by not specifying an Availability Zone in
> your request or choosing us-east-1d, us-east-1b, us-east-1c,
> us-east-1f.