azure: validation: machinepool: sort slice before comparing
We cannot rely on any ordering from iterating over a Golang map. If we
do, we might fail unit tests because the values we compare with are
different:
```
 --- FAIL: TestValidateMachinePool (0.00s)
    --- FAIL: TestValidateMachinePool/securityType_set_to_ConfidentialVM_but_securityEncryptionType_is_invalid (0.00s)
        machinepool_test.go:610:
            	Error Trace:	/go/src/github.com/openshift/installer/pkg/types/azure/validation/machinepool_test.go:610
            	Error:      	Expect "test-path.defaultMachinePlatform.osDisk.securityProfile.securityEncryptionType: Unsupported value: "invalidSecurityEncryptionType": supported values: "DiskWithVMGuestState", "VMGuestStateOnly"" to match "^test-path.defaultMachinePlatform.osDisk.securityProfile.securityEncryptionType: Unsupported value: "invalidSecurityEncryptionType": supported values: "VMGuestStateOnly", "DiskWithVMGuestState"$"
            	Test:       	TestValidateMachinePool/securityType_set_to_ConfidentialVM_but_securityEncryptionType_is_invalid
FAIL
```
Using a sorted list resolves the problem.