OpenStack: Use UTF-8 locales in CI container image
The POSIX default locales cause the following error while retrieving
nova console logs:

    UnicodeEncodeError: 'ascii' codec can't encode characters in position

As explained in [1] we should set the locales to UTF8 to workaround the
issue.

[1] https://docs.openstack.org/python-novaclient/train/cli/nova.html#nova-console-log